/*
 * Hytale API
 * Hytale Official API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Article;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ArticlesApi
 */
@Ignore
public class ArticlesApiTest {

    private final ArticlesApi api = new ArticlesApi();

    
    /**
     * 
     *
     * Get list of articles published
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getArticleBySlugTest() throws ApiException {
        String slug = null;
        Article response = api.getArticleBySlug(slug);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get list of articles published
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getArticlesTest() throws ApiException {
        Boolean featuredOnly = null;
        List<Article> response = api.getArticles(featuredOnly);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get list of articles published on a specific month of an year
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getArticlesOfMonthAndYearTest() throws ApiException {
        Integer year = null;
        Integer month = null;
        List<Article> response = api.getArticlesOfMonthAndYear(year, month);

        // TODO: test validations
    }
    
}
